demo-46

diff --git a/.github/workflows/packer-build.yml b/.github/workflows/packer-build.yml
--- a/.github/workflows/packer-build.yml
+++ b/.github/workflows/packer-build.yml
@@ -328,59 +328,124 @@
 #             fi
 #           done
 
-name: packer build
-  run: |
-    packer build -var "region=$AMI_REGION" \
-    -var "ssh_username=$LOGIN_USERNAME" \
-    -var "instance_type=$INSTANCE_TYPE" \
-    -var "ami_users=$AMISHAREDOWNER" \
-    -var "owners=$AMIOWNERID" aws-ubuntu.pkr.hcl
-    ami_id=$(cat manifest.json | grep -o '"artifact_id": "[^"]*' | cut -d'"' -f4 | cut -d':' -f2)
-    echo $ami_id
-    echo "AMI_ID=$ami_id" >> $GITHUB_ENV
+name: Packer Build and Launch Template Update
 
-name: Set AMI ID as a variable
-  run: echo "ami_id=${{ env.AMI_ID }}"
+on:
+  push:
+    branches:
+      - main
 
-name: Create New Version of Launch Template
-  run: |
-    export AWS_ACCESS_KEY_ID=${{ secrets.DEMO_AWS_ACCESS_KEY_ID }}
-    export AWS_SECRET_ACCESS_KEY=${{ secrets.DEMO_AWS_SECRET_ACCESS_KEY }}
-    aws ec2 create-launch-template-version \
-    --launch-template-id ${{ env.LAUNCH_TEMPLATE_ID }} \
-    --version-description "New version with AMI ${{ env.AMI_ID }}" \
-    --region $AWS_REGION \
-    --source-version 1 \
-    --launch-template-data '{"ImageId": "${{ env.AMI_ID }}" }'
+jobs:
+  packer_build:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v2
 
-name: Apply Launch Template Refresh
-  run: |
-    export AWS_ACCESS_KEY_ID=${{ secrets.DEMO_AWS_ACCESS_KEY_ID }}
-    export AWS_SECRET_ACCESS_KEY=${{ secrets.DEMO_AWS_SECRET_ACCESS_KEY }}
+      - name: Setup Node.js
+        uses: actions/setup-node@v2
+        with:
+          node-version: 16.x
+          cache: 'npm'
 
-    refresh_response=$(aws autoscaling start-instance-refresh \
-    --auto-scaling-group-name $AUTO_SCALE_GROUP_ID \
-    --desired-configuration '{"LaunchTemplate" : { "LaunchTemplateId":"${{ env.LAUNCH_TEMPLATE_ID }}", "Version":"$Latest" }}' \
-    --region $AWS_REGION \
-    --query 'InstanceRefreshId' \
-    --output text)
+      - name: Install npm modules
+        run: npm ci
 
-    while true; do
-      refresh_status=$(aws autoscaling describe-instance-refreshes \
-        --auto-scaling-group-name $AUTO_SCALE_GROUP_ID \
-        --instance-refresh-ids $refresh_response \
-        --region $AWS_REGION \
-        --query 'InstanceRefreshes[0].Status' \
-        --output text)
+      - name: Fund npm
+        run: npm fund
 
-      if [ "$refresh_status" == "Pending" ] || [ "$refresh_status" == "InProgress" ]; then
-        echo "Instance refresh is still in progress. Waiting..."
-        sleep 60  # Wait for 60 seconds before checking again
-      elif [ "$refresh_status" == "Successful" ]; then
-        echo "Instance refresh completed successfully."
-        break  # Exit the loop when refresh is successful
-      else
-        echo "Error: Instance refresh failed or encountered an unexpected status: $refresh_status"
-        exit 1  # Exit with an error if refresh fails or has unexpected status
-      fi
-    done
+      - name: Start MySQL Server
+        run: sudo systemctl start mysql
+
+      - name: Zip the file
+        uses: thedoctor0/zip-release@0.7.1
+        with:
+          type: 'zip'
+          filename: 'webapp.zip'
+          exclusions: '*.git* /*node_modules/* '
+
+      - name: Write variables into env file
+        run: |
+          echo "DATABASE_HOST: ${{ secrets.DATABASE_HOST }}" >> .env
+          echo "DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}" >> .env
+          echo "DATABASE_NAME: ${{ secrets.DATABASE_NAME }}" >> .env
+          echo "DATABASE_HOST: ${{ secrets.DATABASE_HOST }}" >> .env
+          echo "PORT: ${{ secrets.PORT }}" >> .env
+          echo "below are environment variables"
+          cat .env
+        shell: bash
+
+      - name: Setup Packer
+        uses: hashicorp/setup-packer@v1
+        with:
+          version: 1.9.4
+
+      - name: Check version of Packer
+        run: packer -v
+
+      - name: Add required plugins
+        run: packer init .
+
+      - name: Format Packer content
+        run: packer fmt .
+
+      - name: Validate Packer
+        run: packer validate .
+
+      - name: Build AMI
+        run: |
+          packer build -var "region=${{ vars.AMI_REGION }}" \
+          -var "ssh_username=${{ vars.LOGIN_USERNAME }}" \
+          -var "instance_type=${{ vars.INSTANCE_TYPE }}" \
+          -var "ami_users=${{ vars.AMISHAREDOWNER }}" \
+          -var "owners=${{ vars.AMIOWNERID }}" aws-ubuntu.pkr.hcl
+
+          ami_id=$(cat manifest.json | grep -o '"artifact_id": "[^"]*' | cut -d'"' -f4 | cut -d':' -f2)
+          echo $ami_id
+          echo "AMI_ID=$ami_id" >> $GITHUB_ENV
+
+      - name: Set AMI ID as a variable
+        run: echo "AMI_ID=${{ env.AMI_ID }}"
+
+      - name: Create New Version of Launch Template
+        run: |
+          export AWS_ACCESS_KEY_ID=${{ secrets.DEMO_AWS_ACCESS_KEY_ID }}
+          export AWS_SECRET_ACCESS_KEY=${{ secrets.DEMO_AWS_SECRET_ACCESS_KEY }}
+          aws ec2 create-launch-template-version \
+          --launch-template-id ${{ vars.LAUNCH_TEMPLATE_ID }} \
+          --version-description "New version with AMI ${{ env.AMI_ID }}" \
+          --region ${{ secrets.AMI_REGION }} \
+          --source-version 1 \
+          --launch-template-data '{"ImageId": "${{ env.AMI_ID }}" }'
+
+      - name: Apply Launch Template Refresh
+        run: |
+          export AWS_ACCESS_KEY_ID=${{ secrets.DEMO_AWS_ACCESS_KEY_ID }}
+          export AWS_SECRET_ACCESS_KEY=${{ secrets.DEMO_AWS_SECRET_ACCESS_KEY }}
+
+          refresh_response=$(aws autoscaling start-instance-refresh \
+          --auto-scaling-group-name ${{ vars.AUTO_SCALE_GROUP_ID }}  \
+          --desired-configuration '{"LaunchTemplate" : { "LaunchTemplateId":"${{ vars.LAUNCH_TEMPLATE_ID }}", "Version":"$Latest" }}' \
+          --region ${{ vars.AMI_REGION }} \
+          --query 'InstanceRefreshId' \
+          --output text)
+
+          while true; do
+            refresh_status=$(aws autoscaling describe-instance-refreshes \
+              --auto-scaling-group-name ${{ vars.AUTO_SCALE_GROUP_ID }}  \
+              --instance-refresh-ids $refresh_response \
+              --region ${{ vars.AMI_REGION }} \
+              --query 'InstanceRefreshes[0].Status' \
+              --output text)
+
+            if [ "$refresh_status" == "Pending" ] || [ "$refresh_status" == "InProgress" ]; then
+              echo "Instance refresh is still in progress. Waiting..."
+              sleep 60
+            elif [ "$refresh_status" == "Successful" ]; then
+              echo "Instance refresh completed successfully."
+              break
+            else
+              echo "Error: Instance refresh failed or encountered an unexpected status: $refresh_status"
+              exit 1
+            fi
+          done
